version: "2.6.1"
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    image: guzhii/frontend
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
      - "./:/node_modules"